apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wordpress-app

resources:
  - deployment.yaml
  - persistent-volume.yaml
  - secret.yaml

images:
  - name: wordpress
    newName: 225320283044.dkr.ecr.eu-central-1.amazonaws.com/cicd-infra
    newTag: wordpress-dev-7
  - name: nginx
    newName: 225320283044.dkr.ecr.eu-central-1.amazonaws.com/cicd-infra
    newTag: nginx-dev-7