apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wordpress

resources:
  - deployment.yaml
  - service.yaml
  - persistent-volume.yaml
  - secret.yaml

images:
  - name: wordpress
    newName: 225320283044.dkr.ecr.eu-central-1.amazonaws.com/cicd-infra
    newTag: wordpress-${ENVIRONMENT}-0  # Placeholder, updated by Jenkins
  - name: nginx
    newName: 225320283044.dkr.ecr.eu-central-1.amazonaws.com/cicd-infra
    newTag: nginx-${ENVIRONMENT}-0      # Placeholder, updated by Jenkins