---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-data-claim
  namespace: wordpress-app
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi