---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: wordpress-app
type: Opaque
data:
  mysql-root-password: d3JkbHByczEyMw==  # Base64 encoded password
  mysql-password: d3JkUHdzMTIz          # Base64 encoded user password
